package:
  name: gaff2xml
  version: 0.6.0

source:
    git_url: https://github.com/choderalab/gaff2xml.git
    git_tag: 0.6

requirements:
  build:
    - python
    - cython
    - scipy
    - setuptools
    - mdtraj
    - openmm
    - ambermini

  run:
    - python
    - pandas
    - scipy
    - mdtraj
    - openmm
    - ambermini

about:
  home: https://github.com/choderalab/gaff2xml
  license: GNU Lesser General Public License v2 or later (LGPLv2+)

