package:
  name: repex
  version: !!str dev

source:
  fn: master.zip
  url: https://github.com/choderalab/repex/archive/master.zip

requirements:
  build:
    - python
    - cython
    - numpy
    - scipy
    - setuptools
    - mdtraj
    - openmm     
    - netcdf4
    - mpi4py    

  run:
    - python
    - pandas
    - scipy
    - mdtraj
    - openmm       
    - netcdf4
    - mpi4py    

build:
  script: $PYTHON setup.py install

test:
  commands:
    - nosetests

about:
  home: https://github.com/choderalab/repex
  license: GNU Lesser General Public License v2 or later (LGPLv2+)
  summary: OpenMM replica exchange utilities
