package:
  name: pybtex-docutils
  version: !!str 0.2.0

source:
  url: https://pypi.python.org/packages/source/p/pybtex-docutils/pybtex-docutils-0.2.0.zip#md5=8ac5adee871986aba7dc9ef808f8a8ae
  fn: pybtex-docutils-0.2.0.zip

build:
  preserve_egg_dir: True

requirements:
  build:
    - setuptools
    - python
    - pybtex

  run:
    - python
    - pybtex

about:
  home: https://pypi.python.org/pypi/pybtex-docutils
  license: MIT
