package:
  name: private-package-test
  version: 1.0

source:
  fn: pymbar-master.zip
  url: https://github.com/choderalab/pymbar/archive/master.zip

requirements:
  build:
    - python
    - setuptools
    - numpy
    - scipy

  run:
    - numpy
    - scipy

build:
  script: $PYTHON setup.py install

test:

about:
  home:
  license: LGPL
  summary: Private package test
