package:
  name: yank
  version: !!str 0.0.0

source:
  fn: master.zip
  url: https://github.com/choderalab/yank/archive/master.zip

requirements:
  build:
    - python
    - setuptools
    - scipy
    - docopt
    - netcdf4
    - openmmtools
    - pymbar

  run:
    - openmm
    - scipy
    - numpy
    - netcdf4
    - mpi4py
    - repex
    - ambermini
    - docopt
    - netcdf4
    - openmmtools
    - pymbar

#test:
#  commands:
#    - nosetests

about:
  home: http://github.com/choderalab/yank
  license: GNU Lesser General Public License v2 or later (LGPLv2+)
  summary: GPU-accelerated alchemical free energy calculations.
