package:
  name: yank
  version: !!str dev

source:
  fn: master.zip
  url: https://github.com/choderalab/yank/archive/master.zip

requirements:
  build:
    - python
    - setuptools
    - scipy

  run:
    - openmm
    - scipy
    - numpy
    - netcdf4
    - mpi4py
    - repex
    - ambermini

build:
  script: $PYTHON setup.py install

test:
  commands:
    - nosetests

about:
  home: http://github.com/choderalab/yank
  license: GNU Lesser General Public License v2 or later (LGPLv2+)
  summary: GPU-accelerated alchemical free energy calculations.
