package:
  name: yank
  version: d342139d92d1ce893d89f5d60ef04d3b8ba98211

source:
  fn: yank-master.zip
  url: https://github.com/choderalab/yank/archive/d342139d92d1ce893d89f5d60ef04d3b8ba98211.zip
  md5: 2e2bb140bc32d3146c82a4773ab5dd98

requirements:
  build:

  run:
    - openmm
    - scipy
    - numpy
    - ambermini
    - netcdf4
    - mpi4py

test:
  commands:
    #- nosetests

about:
  home: http://github.com/choderalab/yank
  license: LGPL
  summary: Insanity in a box.
