package:
  name: openmm
  version: master

source:
  url: https://github.com/pandegroup/openmm/archive/master.tar.gz
  fn: master.tar.gz

  patches:
    - plugin-dir.patch

build:
  number: 0

requirements:
  build:
    - cmake
    - python
    - fftw3f

  run:
    - python
    - fftw3f

about:
  home: http://openmm.org
  license: MIT
