package:
  name: openmm
  version: 6.2.dev0

source:
  url: https://github.com/pandegroup/openmm/archive/master.tar.gz
  fn: master.tar.gz

  patches:
    - plugin-dir.patch

build:
  number: 0

requirements:
  build:
    - cmake
    - python
    - fftw3f
    - sphinx
    - pip
    # - swig # leave out unless we use VM with workaround because conda swig is broken

  run:
    - python
    - fftw3f

about:
  home: http://openmm.org
  license: MIT
