package:
  name: openmm
  version: 6.0.1

source:
  url: https://github.com/SimTk/openmm/archive/6.0.1.zip
  fn: source.zip
  patches:
    - plugin-dir.patch

build:
  number: 2

requirements:
  build:
    - cmake
    - python
    - fftw3f

  run:
    - python
    - fftw3f

about:
  home: https://simtk.org/home/openmm
  license: GPL
