package:
  name: openmm
  version: 6.2

source:
  url: https://github.com/pandegroup/openmm/archive/6.2.tar.gz
  fn: 6.2.tar.gz

  patches:
    - plugin-dir.patch

build:
  number: 1
  preserve_egg_dir: yes

requirements:
  build:
    # on windows, need to install cmake manually
    - cmake  # [not win]
    - python
    - fftw3f # [not win]
    - sphinx
    - sphinxcontrib-bibtex
    - swig

  run:
    - python
    - fftw3f # [not win]

test:
  imports:
    - simtk
    - simtk.openmm
  commands:
    - python -m simtk.testInstallation

about:
  home: http://openmm.org
  license: LGPL and MIT
  summary: A high performance toolkit for molecular simulation.
