package:
  name: openmmtools
  version: 0.6.0

source:
    git_url: https://github.com/choderalab/openmmtools.git
    git_tag: 0.6

build:
  preserve_egg_dir: True
  number: 1

requirements:
  build:
    - python
    - cython
    - numpy
    - scipy
    - nose
    - setuptools
    - openmm
    - jinja2

  run:
    - python
    - scipy
    - openmm
    - nose
    - setuptools
    - jinja2


test:
  requires:
    - nose
  imports:
    - openmmtools
  commands:
    - nosetests openmmtools --with-doctest --verbosity=2 --nocapture

about:
  home: https://github.com/choderalab/openmmtools
  license: GNU Lesser General Public License v2 or later (LGPLv2+)
