package:
  name: pymbar
  version: 2.1beta0

source:
  url: https://github.com/choderalab/pymbar/archive/v2.1.0-beta.tar.gz
  fn: v2.1.0-beta.tar.gz

requirements:
  build:
    - python
    - setuptools
    - numpy
    - scipy

  run:
    - numpy
    - scipy

test:
  commands:
    - nosetests

  requires:
    - nose

about:
  home: http://github.com/choderalab/pymbar
  license: LGPL
  summary: Python implementation of the multistate Bennett acceptance ratio (MBAR).
