package:
  name: pymbar
  version: 2.1beta0

source:
  url: https://github.com/choderalab/pymbar/archive/v2.1.0-beta.tar.gz
  fn: master.tar.gz

requirements:
  build:
    - python
    - setuptools
    - numpy
    - scipy

  run:
    - numpy
    - scipy

build:
  script: $PYTHON setup.py install

test:
  commands:
    - nosetests
    
about:
  home: http://github.com/choderalab/pymbar
  license: LGPL
  summary: Python implementation of the multistate Bennett acceptance ratio (MBAR).
