package:
  name: scs
  version: !!str 1.0.7_m1

source:
  git_url: git@github.com:cvxgrp/scs.git
  git_branch: master

  patches:
    - clapack.patch

build:
  number: 1

requirements:
  build:
    - python
    - numpy
    - clapack

  run:
    - python
    - numpy
    - scipy

test:
  # Python imports
  imports:
    - scs

about:
  home: http://github.com/cvxgrp/scs
  license: GPLv3
  summary: 'scs: splittling cone solver'
