package:
  name: ecos
  version: !!str 1.1.1_m1

source:
  git_url: git@github.com:embotech/ecos-python.git
  git_branch: develop

requirements:
  build:
    - python
    - setuptools
    - numpy >=1.7
    - scipy >=0.12

  run:
    - python
    - setuptools
    - numpy >=1.7
    - scipy >=0.12

test:
  # Python imports
  imports:
    - ecos

about:
  home: https://github.com/embotech/ecos
  license: GPLv3
  summary: 'A lightweight conic solver for second-order cone programming.'
