package:
  name: ecos
  version: !!str 1.1.0

source:
  fn: ecos-1.1.0.tar.gz
  url: https://pypi.python.org/packages/source/e/ecos/ecos-1.1.0.tar.gz
  md5: f613c75198996093db5f894ad3f64385

requirements:
  build:
    - python
    - setuptools
    - numpy >=1.7
    - scipy >=0.12

  run:
    - python
    - setuptools
    - numpy >=1.7
    - scipy >=0.12

test:
  # Python imports
  imports:
    - ecos

about:
  home: https://github.com/embotech/ecos
  license: GPLv3
  summary: 'A lightweight conic solver for second-order cone programming.'
