package:
  name: cluster_utils
  version: !!str 0.1

source:
   git_url: https://github.com/choderalab/cluster-utils
   git_tag: 0.1

build:
  entry_points:
    - build_mpirun_configfile = cluster_utils.build_mpirun_configfile:main

requirements:
  build:
    - python
    - distribute

  run:
    - python

about:
  home: https://github.com/choderalab/cluster-utils
  license: GNU Lesser General Public License v2 or later (LGPLv2+)
  summary: Tools for use in compute cluster environments.
