package:
  name: mixtape
  version: !!str 0.2.2

source:
  fn: 0.2.2.tar.gz
  url: https://github.com/rmcgibbo/mixtape/archive/0.2.2.tar.gz

build:
  preserve_egg_dir: True

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 1

requirements:
  build:
    - python
    - setuptools
#    - numpy  # Don't include numpy here because it requires you to build a separate conda packages for each version.
    - scipy
    - fastcluster
    - pytables
    - pyyaml
    - mdtraj
    - scikit-learn    

  run:
    - python
#    - numpy  # Don't include numpy here because it requires you to build a separate conda packages for each version.
    - scipy
    - fastcluster
    - pytables
    - pyyaml
    - mdtraj
    - scikit-learn    

about:
  home: https://github.com/rmcgibbo/mixtape
  license: GPLv3.0
  summary: 'mixtape: machine learning models for conformational dynamics'

