package:
  name: mixtape
  #version: !!str 0.2.2
  version: 0.3

source:
  #fn: 0.2.2.tar.gz
  #url: https://github.com/rmcgibbo/mixtape/archive/0.2.2.tar.gz
  fn: master.zip
  url: https://github.com/rmcgibbo/mixtape/archive/master.zip

build:
  preserve_egg_dir: True

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 1

requirements:
  build:
    - python
    - setuptools
    - cython    
#    - numpy  # Don't include numpy here because it requires you to build a separate conda packages for each version.
    - scipy
    - pytables
    - pyyaml
    - mdtraj
    - scikit-learn    

  run:
    - python
    - cython
#    - numpy  # Don't include numpy here because it requires you to build a separate conda packages for each version.
    - scipy
    - pytables
    - pyyaml
    - mdtraj
    - scikit-learn    

about:
  home: https://github.com/rmcgibbo/mixtape
  license: GPLv3.0
  summary: 'mixtape: machine learning models for conformational dynamics'

