package:
  name: cvxpy
  version: !!str 0.2.15

source:
  fn: cvxpy-0.2.15.tar.gz
  url: https://pypi.python.org/packages/source/c/cvxpy/cvxpy-0.2.15.tar.gz
  md5: 5cabc53f8d4630ff5976c3a9601ae0d7
#  patches:
   # List any patch files here
   # - fix.patch

requirements:
  build:
    - python
    - setuptools
    - cvxopt
    - ecos
    - scs
    - toolz
    - numpy
    - scipy

  run:
    - python
    - cvxopt
    - ecos
    - scs
    - toolz
    - numpy
    - scipy

test:
  # Python imports
  imports:
    - cvxpy
    - cvxpy.atoms
    - cvxpy.atoms.affine
    - cvxpy.atoms.elementwise
    - cvxpy.constraints
    - cvxpy.expressions
    - cvxpy.expressions.constants
    - cvxpy.expressions.variables
    - cvxpy.interface
    - cvxpy.interface.cvxopt_interface
    - cvxpy.interface.numpy_interface
    - cvxpy.lin_ops
    - cvxpy.problems
    - cvxpy.problems.problem_data
    - cvxpy.problems.solvers
    - cvxpy.tests
    - cvxpy.utilities

  commands:
    - nosetests cvxpy

  requires:
    - nose

about:
  home: http://github.com/cvxgrp/cvxpy/
  license: GPLv3
  summary: 'A domain-specific language for modeling convex optimization problems in Python.'
