package:
  name: pyemma
  version: !!str 1.0.1

source:
  fn: pyEMMA-v1.0.1.tar.gz
  url: https://pypi.python.org/packages/source/p/pyEMMA/pyEMMA-1.0.1.tar.gz
  md5: 8958b71454687ad1b6861b48ddf32188 

requirements:
  build:
    - python
    - setuptools
# not needed actually, since we're deploying pre-cythonized sources
    - cython >=0.20
    - numpy >=1.6.0
    - scipy >=0.11
    - pystallone >=1.0.0b3

  run:
    - python
    - setuptools
    - numpy >=1.6.0
    - scipy >=0.11
    - pystallone >=1.0.0b3
    - argparse # [py26]

test:
  imports:
    - pyemma
#  commands:
#    - mm_cluster
about:
  home: http://github.com/markovmodel/PyEMMA
  license: BSD 2-Clause License
  summary: "EMMA: Emma's Markov Model Algorithms"


