package:
  name: mdtraj
  version: !!str 1.1.0

source:
  git_url: https://github.com/mdtraj/mdtraj
  git_tag: 1.1.0

build:
  number: 0
  entry_points:
    - mdconvert = mdtraj.scripts.mdconvert:entry_point
    - mdinspect = mdtraj.scripts.mdinspect:entry_point

requirements:
  build:
    - python
    - cython
    - numpy
    - setuptools

  run:
    - python
    - numpy
    - scipy
    - pandas
    - scripttest

about:
  home: http://mdtraj.org/
  license: GNU Lesser General Public License v2 or later (LGPLv2+)
  summary: A modern, open library for the analysis of molecular dynamics trajectories
