package:
  name: mdtraj
  version: !!str 1.3.0

source:
  fn: mdtraj-1.3.0.tar.gz
  url: https://pypi.python.org/packages/source/m/mdtraj/mdtraj-1.3.0.tar.gz#md5=6ffcde3e8a04eb0d9c952391e86ae9fb
  md5: 6ffcde3e8a04eb0d9c952391e86ae9fb

build:
  number: 0
  entry_points:
    - mdconvert = mdtraj.scripts.mdconvert:entry_point
    - mdinspect = mdtraj.scripts.mdinspect:entry_point

requirements:
  build:
    - python
    - cython
    - numpy
    - setuptools
    - scripttest

  run:
    - python
    - numpy
    - scipy
    - pandas
    - scripttest

about:
  home: http://mdtraj.org/
  license: GNU Lesser General Public License v2 or later (LGPLv2+)
  summary: A modern, open library for the analysis of molecular dynamics trajectories
