package:
  name: mdtraj
  version: !!str 1.0.0

source:
  fn: mdtraj-1.0.0.tar.gz
  url: https://pypi.python.org/packages/source/m/mdtraj/mdtraj-1.0.0.tar.gz#md5=357cc06f5bcce6fb2aa073224bdcf389

build:
  number: 0
  entry_points:
    - mdconvert = mdtraj.scripts.mdconvert:entry_point
    - mdinspect = mdtraj.scripts.mdinspect:entry_point

requirements:
  build:
    - python
    - cython
    - numpy
    - setuptools

  run:
    - python
    - numpy
    - scipy
    - pandas

about:
  home: http://mdtraj.org/
  license: GNU Lesser General Public License v2 or later (LGPLv2+)
