package:
  name: msmbuilder
  version: !!str 2.8.2

source:
  fn: msmbuilder-2.8.2.tar.gz
  url: https://pypi.python.org/packages/source/m/msmbuilder/msmbuilder-2.8.2.tar.gz

build:
  preserve_egg_dir: True

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 1

requirements:
  build:
    - python
    - setuptools
#    - numpy  # Don't include numpy here because it requires you to build a separate conda packages for each version.
    - scipy
    - fastcluster
    - pytables
    - pyyaml
    - mdtraj

  run:
    - python
#    - numpy  # Don't include numpy here because it requires you to build a separate conda packages for each version.
    - scipy
    - fastcluster
    - pytables
    - pyyaml
    - mdtraj

test:
  # Python imports
  #imports:
  #  - msmbuilder.project
  #  - msmbuilder
  #  - msmbuilder.scripts
  #  - msmbuilder.lumping
  #  - msmbuilder.metrics
  #  - msmbuilder.reduce
  #  - msmbuilder.geometry

  #commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://msmbuilder.org
  license: GPLv3.0
  summary: 'MSMBuilder: a python library for Markov state models of conformational dynamics'

