package:
  name: pdbfixer
  version: master

source:
  fn: master.zip
  url: https://github.com/SimTk/pdbfixer/archive/master.zip

requirements:
  build:
    - python
    - setuptools
    - openmm
    - numpy

  run:
    - python
    - openmm
    - numpy

build:
  script: $PYTHON setup.py install

test:
  commands:
#    - nosetests

about:
  home: http://github.com/simtk/pdbfixer
  license: free
  summary: PDBFixer fixes problems in PDB files to prepare them for molecular simulation.
