package:
  name: pdbfixer
  version: 1.1

source:
  fn: v1.1.tar.gz
  url: https://github.com/pandegroup/pdbfixer/archive/v1.1.tar.gz

requirements:
  build:
    - python
    - setuptools
    - openmm
    - numpy

  run:
    - python
    - openmm
    - numpy

test:
  commands:
#    - nosetests

about:
  home: http://github.com/simtk/pdbfixer
  license: free
  summary: PDBFixer fixes problems in PDB files to prepare them for molecular simulation.
