package:
  name: ambermini
  version: 13

source:
  fn: ambermini-master.zip
  url: https://github.com/swails/ambermini/archive/master.zip
  md5: af1781384c81cd07dc1d2cd54d9054e7

requirements:
  build:
    - zlib
  run:
    - zlib

test:
  commands:

about:
  home: http://ambermd.org/AmberTools-get.html
  license: LGPL
  summary: A stripped-down version of AmberTools 13 containing antechamber, sqm, and tleap